Rails.application.routes.draw do
  # NHO: this is a lot of routes that your application supports -
  # and I would venture that not all of these routes are being used,
  # would recommend limiting the number of routes tha is generated by resources to only get the routes you need

  root "continents#index"
  # NHO: app errors at `/destinations`...
  resources :destinations, only: [:index, :show, :create] do
    resources :activities
  end

  resources :activities do
    resources :reviews
  end

  resources :reviews # NHO: would anyone ever go to see a list of all reviews / or only a single review
  resources :continents # NHO: probably want to limit these routes
  resources :continents do
    resources :destinations
  end
end
